spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/leconsulat}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:1996}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false

logging:
  level:
    com.leconsulat: INFO
